apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: maxsectorskb
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Custom OpenShift maxsectorskb profile
      include=openshift-node
      [sysfs]
      # maxsectorskb
      /sys/block/dm-0/queue/max_sectors_kb=64
    name: maxsectorskb
  recommend:
  - match:
    - label: node-role.kubernetes.io/master
    priority: 20
    profile: maxsectorskb
